interface GameSeed {
  title: string;
  platform: string;
  genre: string;
  releaseYear: number;
  developer: string;
  publisher: string;
  description: string;
}

export const gameData: GameSeed[] = [
  // ─── NES (1985) ────────────────────────────────────
  { title: 'Super Mario Bros.', platform: 'nes', genre: 'platformer', releaseYear: 1985, developer: 'Nintendo', publisher: 'Nintendo', description: 'The game that saved the video game industry. Mario rescues Princess Peach from Bowser.' },
  { title: 'Super Mario Bros. 3', platform: 'nes', genre: 'platformer', releaseYear: 1990, developer: 'Nintendo', publisher: 'Nintendo', description: 'Widely considered the best 8-bit platformer. Mario gains power-ups and a world map.' },
  { title: 'The Legend of Zelda', platform: 'nes', genre: 'adventure', releaseYear: 1986, developer: 'Nintendo', publisher: 'Nintendo', description: 'The original open-world adventure. Link explores Hyrule to defeat Ganon.' },
  { title: 'Zelda II: The Adventure of Link', platform: 'nes', genre: 'adventure', releaseYear: 1988, developer: 'Nintendo', publisher: 'Nintendo', description: 'A unique side-scrolling entry in the Zelda series with RPG elements.' },
  { title: 'Metroid', platform: 'nes', genre: 'action', releaseYear: 1986, developer: 'Nintendo', publisher: 'Nintendo', description: 'The atmospheric debut of Samus Aran on planet Zebes.' },
  { title: 'Castlevania', platform: 'nes', genre: 'action', releaseYear: 1986, developer: 'Konami', publisher: 'Konami', description: 'Simon Belmont battles Dracula and his minions through Transylvania.' },
  { title: 'Castlevania III: Dracula\'s Curse', platform: 'nes', genre: 'action', releaseYear: 1989, developer: 'Konami', publisher: 'Konami', description: 'The NES Castlevania epic with multiple characters and branching paths.' },
  { title: 'Mega Man 2', platform: 'nes', genre: 'action', releaseYear: 1988, developer: 'Capcom', publisher: 'Capcom', description: 'The pinnacle of classic Mega Man. Iconic Robot Masters and soundtrack.' },
  { title: 'Mega Man 3', platform: 'nes', genre: 'action', releaseYear: 1990, developer: 'Capcom', publisher: 'Capcom', description: 'Introduces Mega Man\'s slide and Rush the dog.' },
  { title: 'Contra', platform: 'nes', genre: 'shooter', releaseYear: 1988, developer: 'Konami', publisher: 'Konami', description: 'Famous run-and-gun with the Konami Code. Bill and Lance vs the Red Falcon.' },
  { title: 'Super C', platform: 'nes', genre: 'shooter', releaseYear: 1990, developer: 'Konami', publisher: 'Konami', description: 'The explosive sequel to Contra with overhead and side-scrolling stages.' },
  { title: 'Ninja Gaiden', platform: 'nes', genre: 'action', releaseYear: 1988, developer: 'Tecmo', publisher: 'Tecmo', description: 'Ryu Hayabusa seeks revenge in this brutally difficult action classic.' },
  { title: 'Punch-Out!!', platform: 'nes', genre: 'sports', releaseYear: 1987, developer: 'Nintendo', publisher: 'Nintendo', description: 'Little Mac climbs the ranks to face Mike Tyson in the ultimate boxing match.' },
  { title: 'Excitebike', platform: 'nes', genre: 'racing', releaseYear: 1985, developer: 'Nintendo', publisher: 'Nintendo', description: 'Side-scrolling motocross racing with track editor.' },
  { title: 'Duck Tales', platform: 'nes', genre: 'platformer', releaseYear: 1989, developer: 'Capcom', publisher: 'Capcom', description: 'Scrooge McDuck hunts treasure around the world with his pogo cane.' },
  { title: 'Kirby\'s Adventure', platform: 'nes', genre: 'platformer', releaseYear: 1993, developer: 'HAL Laboratory', publisher: 'Nintendo', description: 'Kirby\'s first NES adventure with the iconic copy ability.' },
  { title: 'Final Fantasy', platform: 'nes', genre: 'rpg', releaseYear: 1987, developer: 'Square', publisher: 'Square', description: 'The original Final Fantasy. Four Warriors of Light battle Chaos.' },
  { title: 'Dragon Warrior', platform: 'nes', genre: 'rpg', releaseYear: 1986, developer: 'Chunsoft', publisher: 'Enix', description: 'The first Dragon Quest game that defined the JRPG genre in Japan.' },
  { title: 'Blaster Master', platform: 'nes', genre: 'action', releaseYear: 1988, developer: 'Sunsoft', publisher: 'Sunsoft', description: 'A unique hybrid of top-down and side-scrolling action.' },
  { title: 'Bubble Bobble', platform: 'nes', genre: 'platformer', releaseYear: 1987, developer: 'Taito', publisher: 'Taito', description: 'Two dinosaurs Bub and Bob trap enemies in bubbles.' },
  { title: 'Chip \'n Dale Rescue Rangers', platform: 'nes', genre: 'platformer', releaseYear: 1990, developer: 'Capcom', publisher: 'Capcom', description: 'Excellent co-op platformer based on the Disney cartoon.' },
  { title: 'Double Dragon II', platform: 'nes', genre: 'beat-em-up', releaseYear: 1989, developer: 'Technos', publisher: 'Technos', description: 'Classic co-op beat-em-up. Billy and Jimmy Lee seek revenge.' },
  { title: 'River City Ransom', platform: 'nes', genre: 'beat-em-up', releaseYear: 1989, developer: 'Technos', publisher: 'Technos', description: 'Open-world beat-em-up with RPG elements and shops.' },
  { title: 'Kid Icarus', platform: 'nes', genre: 'platformer', releaseYear: 1986, developer: 'Nintendo', publisher: 'Nintendo', description: 'Pit battles through the Underworld, Overworld, and Sky Palace.' },
  { title: 'Dr. Mario', platform: 'nes', genre: 'puzzle', releaseYear: 1990, developer: 'Nintendo', publisher: 'Nintendo', description: 'Addictive puzzle game where Mario throws pills at viruses.' },

  // ─── SNES (1991) ──────────────────────────────────
  { title: 'Super Mario World', platform: 'snes', genre: 'platformer', releaseYear: 1990, developer: 'Nintendo', publisher: 'Nintendo', description: 'Mario\'s 16-bit debut with Yoshi. Packed with secrets and hidden exits.' },
  { title: 'Super Metroid', platform: 'snes', genre: 'action', releaseYear: 1994, developer: 'Nintendo', publisher: 'Nintendo', description: 'The third installment in the Metroid series, following bounty hunter Samus Aran on planet Zebes.' },
  { title: 'The Legend of Zelda: A Link to the Past', platform: 'snes', genre: 'adventure', releaseYear: 1991, developer: 'Nintendo', publisher: 'Nintendo', description: 'Link travels between Light and Dark Worlds to save Hyrule.' },
  { title: 'Chrono Trigger', platform: 'snes', genre: 'rpg', releaseYear: 1995, developer: 'Square', publisher: 'Square', description: 'A groundbreaking RPG featuring time travel and multiple endings.' },
  { title: 'Final Fantasy VI', platform: 'snes', genre: 'rpg', releaseYear: 1994, developer: 'Square', publisher: 'Square', description: 'A steampunk fantasy epic with one of the largest casts in the series.' },
  { title: 'Final Fantasy IV', platform: 'snes', genre: 'rpg', releaseYear: 1991, developer: 'Square', publisher: 'Square', description: 'The first truly story-driven Final Fantasy with Cecil\'s redemption arc.' },
  { title: 'Mega Man X', platform: 'snes', genre: 'action', releaseYear: 1993, developer: 'Capcom', publisher: 'Capcom', description: 'A faster, darker take on the Mega Man formula for the SNES.' },
  { title: 'Donkey Kong Country', platform: 'snes', genre: 'platformer', releaseYear: 1994, developer: 'Rare', publisher: 'Nintendo', description: 'Donkey Kong and Diddy Kong fight to reclaim their banana hoard.' },
  { title: 'Donkey Kong Country 2', platform: 'snes', genre: 'platformer', releaseYear: 1995, developer: 'Rare', publisher: 'Nintendo', description: 'Diddy and Dixie Kong search for DK in this superior sequel.' },
  { title: 'Street Fighter II', platform: 'snes', genre: 'fighting', releaseYear: 1992, developer: 'Capcom', publisher: 'Capcom', description: 'The fighting game that defined a generation. Best 16-bit port.' },
  { title: 'Super Mario Kart', platform: 'snes', genre: 'racing', releaseYear: 1992, developer: 'Nintendo', publisher: 'Nintendo', description: 'The game that invented the kart racing genre.' },
  { title: 'EarthBound', platform: 'snes', genre: 'rpg', releaseYear: 1994, developer: 'HAL Laboratory', publisher: 'Nintendo', description: 'A quirky modern-day RPG with psychic kids and alien invasions.' },
  { title: 'Super Castlevania IV', platform: 'snes', genre: 'action', releaseYear: 1991, developer: 'Konami', publisher: 'Konami', description: 'Simon Belmont returns with 8-directional whip control.' },
  { title: 'Contra III: The Alien Wars', platform: 'snes', genre: 'shooter', releaseYear: 1992, developer: 'Konami', publisher: 'Konami', description: 'Run-and-gun chaos with overhead stages and mode 7 effects.' },
  { title: 'Secret of Mana', platform: 'snes', genre: 'rpg', releaseYear: 1993, developer: 'Square', publisher: 'Square', description: 'Action RPG with three-player co-op and a colorful world.' },
  { title: 'Super Punch-Out!!', platform: 'snes', genre: 'sports', releaseYear: 1994, developer: 'Nintendo', publisher: 'Nintendo', description: 'The SNES follow-up to the NES classic boxing game.' },
  { title: 'F-Zero', platform: 'snes', genre: 'racing', releaseYear: 1990, developer: 'Nintendo', publisher: 'Nintendo', description: 'Mode 7 racing at blistering speeds. Captain Falcon\'s debut.' },
  { title: 'Star Fox', platform: 'snes', genre: 'shooter', releaseYear: 1993, developer: 'Nintendo', publisher: 'Nintendo', description: 'Fox McCloud leads Star Fox team in this Super FX 3D shooter.' },
  { title: 'Super Mario RPG: Legend of the Seven Stars', platform: 'snes', genre: 'rpg', releaseYear: 1996, developer: 'Square', publisher: 'Nintendo', description: 'Mario\'s first RPG with timed hits and charming characters.' },
  { title: 'Kirby Super Star', platform: 'snes', genre: 'platformer', releaseYear: 1996, developer: 'HAL Laboratory', publisher: 'Nintendo', description: 'A collection of Kirby mini-games with co-op play.' },
  { title: 'Mortal Kombat II', platform: 'snes', genre: 'fighting', releaseYear: 1993, developer: 'Midway', publisher: 'Acclaim', description: 'The superior MK on SNES with hidden fighters and fatalities.' },
  { title: 'ActRaiser', platform: 'snes', genre: 'action', releaseYear: 1990, developer: 'Quintet', publisher: 'Enix', description: 'Unique mix of platformer and god simulation.' },
  { title: 'TMNT IV: Turtles in Time', platform: 'snes', genre: 'beat-em-up', releaseYear: 1992, developer: 'Konami', publisher: 'Konami', description: 'Arcade-perfect TMNT beat-em-up through time.' },

  // ─── Nintendo 64 (1996) ────────────────────────────
  { title: 'Super Mario 64', platform: 'nintendo-64', genre: 'platformer', releaseYear: 1996, developer: 'Nintendo', publisher: 'Nintendo', description: 'Mario\'s groundbreaking leap into 3D.' },
  { title: 'The Legend of Zelda: Ocarina of Time', platform: 'nintendo-64', genre: 'adventure', releaseYear: 1998, developer: 'Nintendo', publisher: 'Nintendo', description: 'Often cited as the greatest game of all time.' },
  { title: 'The Legend of Zelda: Majora\'s Mask', platform: 'nintendo-64', genre: 'adventure', releaseYear: 2000, developer: 'Nintendo', publisher: 'Nintendo', description: 'A dark, time-loop adventure in Termina.' },
  { title: 'GoldenEye 007', platform: 'nintendo-64', genre: 'shooter', releaseYear: 1997, developer: 'Rare', publisher: 'Nintendo', description: 'The definitive console FPS that defined multiplayer shooters.' },
  { title: 'Perfect Dark', platform: 'nintendo-64', genre: 'shooter', releaseYear: 2000, developer: 'Rare', publisher: 'Nintendo', description: 'GoldenEye\'s spiritual successor with advanced AI and gadgets.' },
  { title: 'Mario Kart 64', platform: 'nintendo-64', genre: 'racing', releaseYear: 1996, developer: 'Nintendo', publisher: 'Nintendo', description: '4-player split-screen kart racing mayhem.' },
  { title: 'Banjo-Kazooie', platform: 'nintendo-64', genre: 'platformer', releaseYear: 1998, developer: 'Rare', publisher: 'Nintendo', description: 'A bear and bird collect-a-thon with humor and charm.' },
  { title: 'Banjo-Tooie', platform: 'nintendo-64', genre: 'platformer', releaseYear: 2000, developer: 'Rare', publisher: 'Nintendo', description: 'The bigger, more ambitious sequel with interconnected worlds.' },
  { title: 'Super Smash Bros.', platform: 'nintendo-64', genre: 'fighting', releaseYear: 1999, developer: 'Nintendo', publisher: 'Nintendo', description: 'Nintendo\'s all-star fighting game that started a phenomenon.' },
  { title: 'Paper Mario', platform: 'nintendo-64', genre: 'rpg', releaseYear: 2000, developer: 'Intelligent Systems', publisher: 'Nintendo', description: 'Mario\'s paper-thin RPG adventure to rescue the Star Spirits.' },
  { title: 'Star Fox 64', platform: 'nintendo-64', genre: 'shooter', releaseYear: 1997, developer: 'Nintendo', publisher: 'Nintendo', description: 'Fox McCloud returns in this on-rails shooter with voice acting.' },
  { title: 'F-Zero X', platform: 'nintendo-64', genre: 'racing', releaseYear: 1998, developer: 'Nintendo', publisher: 'Nintendo', description: '60 FPS anti-gravity racing with 30 racers on track.' },
  { title: 'Diddy Kong Racing', platform: 'nintendo-64', genre: 'racing', releaseYear: 1997, developer: 'Rare', publisher: 'Nintendo', description: 'Kart, plane, and hovercraft racing with a story mode.' },
  { title: 'Pokémon Snap', platform: 'nintendo-64', genre: 'puzzle', releaseYear: 1999, developer: 'HAL Laboratory', publisher: 'Nintendo', description: 'Travel through Pokémon Island taking photos of wild Pokémon.' },
  { title: 'Mario Party', platform: 'nintendo-64', genre: 'strategy', releaseYear: 1998, developer: 'Hudson Soft', publisher: 'Nintendo', description: 'The first Mario Party with 4-player board game action.' },
  { title: 'Conker\'s Bad Fur Day', platform: 'nintendo-64', genre: 'platformer', releaseYear: 2001, developer: 'Rare', publisher: 'Rare', description: 'An adult-oriented platformer with crude humor and great gameplay.' },
  { title: 'Tony Hawk\'s Pro Skater', platform: 'nintendo-64', genre: 'sports', releaseYear: 2000, developer: 'Activision', publisher: 'Activision', description: 'Skateboarding classic with trick combos and great soundtrack.' },
  { title: 'WWF No Mercy', platform: 'nintendo-64', genre: 'fighting', releaseYear: 2000, developer: 'AKI', publisher: 'THQ', description: 'The best wrestling game ever made with deep create-a-wrestler.' },
  { title: 'Wave Race 64', platform: 'nintendo-64', genre: 'racing', releaseYear: 1996, developer: 'Nintendo', publisher: 'Nintendo', description: 'Jet ski racing with realistic wave physics.' },
  { title: 'Resident Evil 2', platform: 'nintendo-64', genre: 'horror', releaseYear: 1999, developer: 'Capcom', publisher: 'Capcom', description: 'The N64 port of the survival horror classic on one cartridge.' },

  // ─── Sega Genesis (1989) ────────────────────────────
  { title: 'Sonic the Hedgehog', platform: 'sega-genesis', genre: 'platformer', releaseYear: 1991, developer: 'Sega', publisher: 'Sega', description: 'Sega\'s mascot debut. Speed through Green Hill Zone.' },
  { title: 'Sonic the Hedgehog 2', platform: 'sega-genesis', genre: 'platformer', releaseYear: 1992, developer: 'Sega', publisher: 'Sega', description: 'Sonic teams up with Tails to stop Dr. Robotnik.' },
  { title: 'Sonic 3 & Knuckles', platform: 'sega-genesis', genre: 'platformer', releaseYear: 1994, developer: 'Sega', publisher: 'Sega', description: 'The ultimate Sonic experience when locked together.' },
  { title: 'Streets of Rage 2', platform: 'sega-genesis', genre: 'beat-em-up', releaseYear: 1992, developer: 'Sega', publisher: 'Sega', description: 'The best beat-em-up on Genesis with an iconic soundtrack.' },
  { title: 'Gunstar Heroes', platform: 'sega-genesis', genre: 'shooter', releaseYear: 1993, developer: 'Treasure', publisher: 'Sega', description: 'Run-and-gun brilliance from Treasure with weapon mixing.' },
  { title: 'Castlevania: Bloodlines', platform: 'sega-genesis', genre: 'action', releaseYear: 1994, developer: 'Konami', publisher: 'Konami', description: 'The only Castlevania on Genesis, featuring the Morris family.' },
  { title: 'Shining Force II', platform: 'sega-genesis', genre: 'strategy', releaseYear: 1993, developer: 'Camelot', publisher: 'Sega', description: 'A tactical RPG classic with a huge cast of characters.' },
  { title: 'Phantasy Star IV', platform: 'sega-genesis', genre: 'rpg', releaseYear: 1993, developer: 'Sega', publisher: 'Sega', description: 'The best Phantasy Star game with comic-style cutscenes.' },
  { title: 'Streets of Rage', platform: 'sega-genesis', genre: 'beat-em-up', releaseYear: 1991, developer: 'Sega', publisher: 'Sega', description: 'The original Streets of Rage with classic Yuzo Koshiro music.' },
  { title: 'Mortal Kombat', platform: 'sega-genesis', genre: 'fighting', releaseYear: 1992, developer: 'Midway', publisher: 'Acclaim', description: 'The blood code made the Genesis version the one to own.' },
  { title: 'NBA Jam', platform: 'sega-genesis', genre: 'sports', releaseYear: 1993, developer: 'Midway', publisher: 'Acclaim', description: 'Arcade basketball with fire, dunks, and "He\'s on fire!"' },
  { title: 'Snatcher', platform: 'sega-genesis', genre: 'adventure', releaseYear: 1994, developer: 'Konami', publisher: 'Konami', description: 'A cyberpunk visual novel from Hideo Kojima.' },
  { title: 'MUSHA', platform: 'sega-genesis', genre: 'shooter', releaseYear: 1990, developer: 'Compile', publisher: 'Toaplan', description: 'A vertically scrolling shoot-em-up with a heavy metal soundtrack.' },
  { title: 'Road Rash II', platform: 'sega-genesis', genre: 'racing', releaseYear: 1992, developer: 'EA', publisher: 'EA', description: 'Motorcycle racing with brutal hand-to-hand combat.' },
  { title: 'ToeJam & Earl', platform: 'sega-genesis', genre: 'action', releaseYear: 1991, developer: 'Johnson Voorsanger', publisher: 'Sega', description: 'Funky aliens explore Earth in this roguelike adventure.' },
  { title: 'Altered Beast', platform: 'sega-genesis', genre: 'beat-em-up', releaseYear: 1989, developer: 'Sega', publisher: 'Sega', description: 'Genesis launch title. Rise from your grave as powerful beasts.' },
  { title: 'Golden Axe', platform: 'sega-genesis', genre: 'beat-em-up', releaseYear: 1989, developer: 'Sega', publisher: 'Sega', description: 'Fantasy beat-em-up classic with three playable characters.' },
  { title: 'Contra: Hard Corps', platform: 'sega-genesis', genre: 'shooter', releaseYear: 1994, developer: 'Konami', publisher: 'Konami', description: 'The hardest Contra game with branching paths.' },
  { title: 'Earthworm Jim', platform: 'sega-genesis', genre: 'platformer', releaseYear: 1994, developer: 'Shiny', publisher: 'Playmates', description: 'A worm in a super suit platforming through gross-out humor.' },
  { title: 'Comix Zone', platform: 'sega-genesis', genre: 'beat-em-up', releaseYear: 1995, developer: 'Sega', publisher: 'Sega', description: 'A beat-em-up set inside a comic book page.' },

  // ─── PlayStation (1994) ────────────────────────────
  { title: 'Final Fantasy VII', platform: 'playstation', genre: 'rpg', releaseYear: 1997, developer: 'Square', publisher: 'Square', description: 'The RPG that brought Japanese role-playing games to the mainstream.' },
  { title: 'Metal Gear Solid', platform: 'playstation', genre: 'action', releaseYear: 1998, developer: 'Konami', publisher: 'Konami', description: 'Tactical espionage action from Hideo Kojima.' },
  { title: 'Castlevania: Symphony of the Night', platform: 'playstation', genre: 'action', releaseYear: 1997, developer: 'Konami', publisher: 'Konami', description: 'Alucard explores Dracula\'s castle in this genre-defining Metroidvania.' },
  { title: 'Resident Evil 2', platform: 'playstation', genre: 'horror', releaseYear: 1998, developer: 'Capcom', publisher: 'Capcom', description: 'Survival horror classic set in Raccoon City.' },
  { title: 'Resident Evil', platform: 'playstation', genre: 'horror', releaseYear: 1996, developer: 'Capcom', publisher: 'Capcom', description: 'The original survival horror that defined the genre.' },
  { title: 'Gran Turismo', platform: 'playstation', genre: 'racing', releaseYear: 1997, developer: 'Polyphony Digital', publisher: 'Sony', description: 'A revolutionary racing simulator.' },
  { title: 'Gran Turismo 2', platform: 'playstation', genre: 'racing', releaseYear: 1999, developer: 'Polyphony Digital', publisher: 'Sony', description: 'More cars, more tracks, more everything.' },
  { title: 'Crash Bandicoot', platform: 'playstation', genre: 'platformer', releaseYear: 1996, developer: 'Naughty Dog', publisher: 'Sony', description: 'Sony\'s mascot platformer. Wumpa fruit, crates, and Aku Aku.' },
  { title: 'Crash Bandicoot 3: Warped', platform: 'playstation', genre: 'platformer', releaseYear: 1998, developer: 'Naughty Dog', publisher: 'Sony', description: 'Time-traveling platformer perfection with vehicle levels.' },
  { title: 'Spyro the Dragon', platform: 'playstation', genre: 'platformer', releaseYear: 1998, developer: 'Insomniac Games', publisher: 'Sony', description: 'A purple dragon collects gems and frees his dragon friends.' },
  { title: 'Tony Hawk\'s Pro Skater 2', platform: 'playstation', genre: 'sports', releaseYear: 2000, developer: 'Activision', publisher: 'Activision', description: 'Best skateboarding game ever. Create-a-skater, manuals, and great levels.' },
  { title: 'Suikoden II', platform: 'playstation', genre: 'rpg', releaseYear: 1998, developer: 'Konami', publisher: 'Konami', description: 'A beloved RPG featuring 108 recruitable characters.' },
  { title: 'Final Fantasy IX', platform: 'playstation', genre: 'rpg', releaseYear: 2000, developer: 'Square', publisher: 'Square', description: 'A return to the series\' fantasy roots with a wonderful cast.' },
  { title: 'Final Fantasy Tactics', platform: 'playstation', genre: 'strategy', releaseYear: 1997, developer: 'Square', publisher: 'Square', description: 'Deep tactical RPG set in the war-torn kingdom of Ivalice.' },
  { title: 'Silent Hill', platform: 'playstation', genre: 'horror', releaseYear: 1999, developer: 'Konami', publisher: 'Konami', description: 'Psychological horror in the fog-shrouded town of Silent Hill.' },
  { title: 'Tekken 3', platform: 'playstation', genre: 'fighting', releaseYear: 1998, developer: 'Namco', publisher: 'Namco', description: 'The best Tekken on PS1 with a deep character roster.' },
  { title: 'Vagrant Story', platform: 'playstation', genre: 'rpg', releaseYear: 2000, developer: 'Square', publisher: 'Square', description: 'A masterpiece of game design. Deep battle system and interconnected level design.' },
  { title: 'Parasite Eve', platform: 'playstation', genre: 'rpg', releaseYear: 1998, developer: 'Square', publisher: 'Square', description: 'A unique blend of survival horror and RPG set in New York.' },
  { title: 'Mega Man X4', platform: 'playstation', genre: 'action', releaseYear: 1997, developer: 'Capcom', publisher: 'Capcom', description: 'X and Zero battle Repliforce in this 32-bit Mega Man.' },
  { title: 'Medal of Honor', platform: 'playstation', genre: 'shooter', releaseYear: 1999, developer: 'DreamWorks Interactive', publisher: 'EA', description: 'World War II FPS with cinematic presentation.' },

  // ─── PlayStation 2 (2000) ──────────────────────────
  { title: 'Shadow of the Colossus', platform: 'playstation-2', genre: 'adventure', releaseYear: 2005, developer: 'Team Ico', publisher: 'Sony', description: 'A lone warrior battles colossal beings to revive a fallen maiden.' },
  { title: 'Final Fantasy X', platform: 'playstation-2', genre: 'rpg', releaseYear: 2001, developer: 'Square', publisher: 'Square', description: 'Tidus and Yuna\'s pilgrimage to defeat Sin in the first PS2 Final Fantasy.' },
  { title: 'Metal Gear Solid 2: Sons of Liberty', platform: 'playstation-2', genre: 'action', releaseYear: 2001, developer: 'Konami', publisher: 'Konami', description: 'Snake and Raiden battle the Patriots on the Big Shell.' },
  { title: 'Metal Gear Solid 3: Snake Eater', platform: 'playstation-2', genre: 'action', releaseYear: 2004, developer: 'Konami', publisher: 'Konami', description: 'Cold War espionage epic. The origin of Big Boss.' },
  { title: 'Grand Theft Auto: Vice City', platform: 'playstation-2', genre: 'action', releaseYear: 2002, developer: 'Rockstar North', publisher: 'Rockstar', description: '80s Miami crime saga with iconic soundtrack.' },
  { title: 'Grand Theft Auto: San Andreas', platform: 'playstation-2', genre: 'action', releaseYear: 2004, developer: 'Rockstar North', publisher: 'Rockstar', description: 'CJ returns to Los Santos in this open-world masterpiece.' },
  { title: 'God of War', platform: 'playstation-2', genre: 'action', releaseYear: 2005, developer: 'Santa Monica Studio', publisher: 'Sony', description: 'Kratos seeks revenge against Ares in this brutal action epic.' },
  { title: 'God of War II', platform: 'playstation-2', genre: 'action', releaseYear: 2007, developer: 'Santa Monica Studio', publisher: 'Sony', description: 'Kratos battles the gods of Olympus.' },
  { title: 'Ratchet & Clank', platform: 'playstation-2', genre: 'platformer', releaseYear: 2002, developer: 'Insomniac Games', publisher: 'Sony', description: 'Lombax and robot duo with crazy weapons and humor.' },
  { title: 'Jak and Daxter: The Precursor Legacy', platform: 'playstation-2', genre: 'platformer', releaseYear: 2001, developer: 'Naughty Dog', publisher: 'Sony', description: 'A collect-a-thon platformer in a vibrant world.' },
  { title: 'Devil May Cry', platform: 'playstation-2', genre: 'action', releaseYear: 2001, developer: 'Capcom', publisher: 'Capcom', description: 'Dante stylishly slays demons in this hack-and-slash classic.' },
  { title: 'Kingdom Hearts', platform: 'playstation-2', genre: 'rpg', releaseYear: 2002, developer: 'Square', publisher: 'Square', description: 'Disney and Final Fantasy crossover action RPG.' },
  { title: 'Persona 4', platform: 'playstation-2', genre: 'rpg', releaseYear: 2008, developer: 'Atlus', publisher: 'Atlus', description: 'A murder mystery RPG set in the Japanese countryside.' },
  { title: 'Silent Hill 2', platform: 'playstation-2', genre: 'horror', releaseYear: 2001, developer: 'Team Silent', publisher: 'Konami', description: 'Psychological horror masterpiece. James searches for his dead wife.' },
  { title: 'Gran Turismo 3', platform: 'playstation-2', genre: 'racing', releaseYear: 2001, developer: 'Polyphony Digital', publisher: 'Sony', description: 'The ultimate driving simulator on PS2.' },
  { title: 'Gran Turismo 4', platform: 'playstation-2', genre: 'racing', releaseYear: 2004, developer: 'Polyphony Digital', publisher: 'Sony', description: 'Over 700 cars and photorealistic graphics for its time.' },
  { title: 'Tony Hawk\'s Pro Skater 3', platform: 'playstation-2', genre: 'sports', releaseYear: 2001, developer: 'Neversoft', publisher: 'Activision', description: 'Revert and manual combos. The best THPS game.' },
  { title: 'Resident Evil 4', platform: 'playstation-2', genre: 'horror', releaseYear: 2005, developer: 'Capcom', publisher: 'Capcom', description: 'Over-the-shoulder survival horror that redefined the series.' },
  { title: 'SSX Tricky', platform: 'playstation-2', genre: 'sports', releaseYear: 2001, developer: 'EA Canada', publisher: 'EA', description: 'Arcade snowboarding with over-the-top tricks and style.' },
  { title: 'Okami', platform: 'playstation-2', genre: 'adventure', releaseYear: 2006, developer: 'Clover Studio', publisher: 'Capcom', description: 'Beautiful cel-shaded adventure with ink brush mechanics.' },

  // ─── Sega Dreamcast (1999) ─────────────────────────
  { title: 'Shenmue', platform: 'sega-dreamcast', genre: 'adventure', releaseYear: 1999, developer: 'Sega AM2', publisher: 'Sega', description: 'Ryo Hazuki seeks revenge in this groundbreaking open-world adventure.' },
  { title: 'Shenmue II', platform: 'sega-dreamcast', genre: 'adventure', releaseYear: 2001, developer: 'Sega AM2', publisher: 'Sega', description: 'Ryo travels to Hong Kong in the next chapter of his epic journey.' },
  { title: 'Jet Set Radio', platform: 'sega-dreamcast', genre: 'action', releaseYear: 2000, developer: 'Smilebit', publisher: 'Sega', description: 'Cel-shaded skating graffiti action in Tokyo-to.' },
  { title: 'SoulCalibur', platform: 'sega-dreamcast', genre: 'fighting', releaseYear: 1999, developer: 'Project Soul', publisher: 'Namco', description: 'Arcade-perfect port of the weapon-based fighter. 60 FPS.' },
  { title: 'Crazy Taxi', platform: 'sega-dreamcast', genre: 'racing', releaseYear: 2000, developer: 'Sega AM3', publisher: 'Sega', description: 'Pick up fares and drive like a maniac to the beat of Offspring.' },
  { title: 'Power Stone', platform: 'sega-dreamcast', genre: 'fighting', releaseYear: 1999, developer: 'Capcom', publisher: 'Capcom', description: '3D arena fighter with item collecting and power-ups.' },
  { title: 'Tony Hawk\'s Pro Skater 2', platform: 'sega-dreamcast', genre: 'sports', releaseYear: 2000, developer: 'Neversoft', publisher: 'Activision', description: 'The definitive version of the best skateboarding game.' },
  { title: 'Skies of Arcadia', platform: 'sega-dreamcast', genre: 'rpg', releaseYear: 2000, developer: 'Overworks', publisher: 'Sega', description: 'Air pirates explore a floating world in this grand RPG.' },
  { title: 'Resident Evil: Code Veronica', platform: 'sega-dreamcast', genre: 'horror', releaseYear: 2000, developer: 'Capcom', publisher: 'Capcom', description: 'Claire Redfield searches for Chris in an Antarctic facility.' },
  { title: 'Marvel vs. Capcom 2', platform: 'sega-dreamcast', genre: 'fighting', releaseYear: 2000, developer: 'Capcom', publisher: 'Capcom', description: '3v3 tag-team fighting with 56 characters.' },
  { title: 'Phantasy Star Online', platform: 'sega-dreamcast', genre: 'rpg', releaseYear: 2000, developer: 'Sega', publisher: 'Sega', description: 'The first online console RPG. Paved the way for future MMOs.' },
  { title: 'Space Channel 5', platform: 'sega-dreamcast', genre: 'puzzle', releaseYear: 1999, developer: 'Sega', publisher: 'Sega', description: 'Rhythm game where reporter Ulala saves the world through dance.' },
  { title: 'Ikaruga', platform: 'sega-dreamcast', genre: 'shooter', releaseYear: 2002, developer: 'Treasure', publisher: 'Treasure', description: 'Puzzle-based shoot-em-up with polarity mechanics.' },
  { title: 'Seaman', platform: 'sega-dreamcast', genre: 'simulation', releaseYear: 2000, developer: 'Vivarium', publisher: 'Sega', description: 'You raise a fish with a human face. Leonard Nimoy narrates.' },
  { title: 'Rez', platform: 'sega-dreamcast', genre: 'shooter', releaseYear: 2001, developer: 'United Game Artists', publisher: 'Sega', description: 'A music-based rail shooter experience.' },

  // ─── Game Boy (1989) ───────────────────────────────
  { title: 'Pokemon Red', platform: 'game-boy', genre: 'rpg', releaseYear: 1996, developer: 'Game Freak', publisher: 'Nintendo', description: 'The game that started a global phenomenon.' },
  { title: 'Pokemon Blue', platform: 'game-boy', genre: 'rpg', releaseYear: 1996, developer: 'Game Freak', publisher: 'Nintendo', description: 'Slightly different version of the Pokemon adventure.' },
  { title: 'Pokemon Yellow', platform: 'game-boy', genre: 'rpg', releaseYear: 1998, developer: 'Game Freak', publisher: 'Nintendo', description: 'Special Pikachu edition based on the anime.' },
  { title: 'Pokemon Gold', platform: 'game-boy', genre: 'rpg', releaseYear: 1999, developer: 'Game Freak', publisher: 'Nintendo', description: 'The second generation expands Pokemon to Johto.' },
  { title: 'Pokemon Crystal', platform: 'game-boy', genre: 'rpg', releaseYear: 2000, developer: 'Game Freak', publisher: 'Nintendo', description: 'The definitive Gen 2 Pokemon experience with animations.' },
  { title: 'Tetris', platform: 'game-boy', genre: 'puzzle', releaseYear: 1989, developer: 'Nintendo', publisher: 'Nintendo', description: 'The addictive puzzle game that sold millions of Game Boys.' },
  { title: 'The Legend of Zelda: Link\'s Awakening', platform: 'game-boy', genre: 'adventure', releaseYear: 1993, developer: 'Nintendo', publisher: 'Nintendo', description: 'Link is stranded on Koholint Island in this dreamlike adventure.' },
  { title: 'Super Mario Land', platform: 'game-boy', genre: 'platformer', releaseYear: 1989, developer: 'Nintendo', publisher: 'Nintendo', description: 'Mario\'s first handheld adventure in Sarasaland.' },
  { title: 'Super Mario Land 2', platform: 'game-boy', genre: 'platformer', releaseYear: 1992, developer: 'Nintendo', publisher: 'Nintendo', description: 'Mario reclaims his castle from Wario in this excellent sequel.' },
  { title: 'Wario Land: Super Mario Land 3', platform: 'game-boy', genre: 'platformer', releaseYear: 1994, developer: 'Nintendo', publisher: 'Nintendo', description: 'Wario stars in his own treasure-hunting platformer.' },
  { title: 'Mega Man V', platform: 'game-boy', genre: 'action', releaseYear: 1994, developer: 'Capcom', publisher: 'Capcom', description: 'Original Game Boy Mega Man with the Stardroid bosses.' },
  { title: 'Kirby\'s Dream Land', platform: 'game-boy', genre: 'platformer', releaseYear: 1992, developer: 'HAL Laboratory', publisher: 'Nintendo', description: 'Kirby\'s first game. Simple, charming, and fun.' },
  { title: 'Donkey Kong', platform: 'game-boy', genre: 'platformer', releaseYear: 1994, developer: 'Nintendo', publisher: 'Nintendo', description: 'The original arcade Donkey Kong completely rebuilt with 100+ levels.' },
  { title: 'Metroid II: Return of Samus', platform: 'game-boy', genre: 'action', releaseYear: 1991, developer: 'Nintendo', publisher: 'Nintendo', description: 'Samus hunts the Metroids on their home planet SR388.' },
  { title: 'Castlevania II: Belmont\'s Revenge', platform: 'game-boy', genre: 'action', releaseYear: 1991, developer: 'Konami', publisher: 'Konami', description: 'Christopher Belmont rescues his son from Dracula.' },
  { title: 'Final Fantasy Legend', platform: 'game-boy', genre: 'rpg', releaseYear: 1989, developer: 'Square', publisher: 'Square', description: 'The first Final Fantasy game on Game Boy. Actually a SaGa title.' },
  { title: 'Gargoyle\'s Quest', platform: 'game-boy', genre: 'action', releaseYear: 1990, developer: 'Capcom', publisher: 'Capcom', description: 'Firebrand the gargoyle in an action-platformer RPG hybrid.' },

  // ─── Game Boy Advance (2001) ────────────────────────
  { title: 'Castlevania: Aria of Sorrow', platform: 'gba', genre: 'action', releaseYear: 2003, developer: 'Konami', publisher: 'Konami', description: 'A standout Metroidvania on the Game Boy Advance.' },
  { title: 'The Legend of Zelda: The Minish Cap', platform: 'gba', genre: 'adventure', releaseYear: 2004, developer: 'Capcom', publisher: 'Nintendo', description: 'Link shrinks down to explore a tiny world in this charming adventure.' },
  { title: 'Metroid Fusion', platform: 'gba', genre: 'action', releaseYear: 2002, developer: 'Nintendo', publisher: 'Nintendo', description: 'Samus faces the SA-X in this atmospheric sequel.' },
  { title: 'Metroid: Zero Mission', platform: 'gba', genre: 'action', releaseYear: 2004, developer: 'Nintendo', publisher: 'Nintendo', description: 'A faithful reimagining of the original Metroid with modern gameplay.' },
  { title: 'Fire Emblem: The Blazing Blade', platform: 'gba', genre: 'strategy', releaseYear: 2003, developer: 'Intelligent Systems', publisher: 'Nintendo', description: 'The first Fire Emblem released outside Japan.' },
  { title: 'Fire Emblem: The Sacred Stones', platform: 'gba', genre: 'strategy', releaseYear: 2004, developer: 'Intelligent Systems', publisher: 'Nintendo', description: 'A more open Fire Emblem with a world map.' },
  { title: 'Golden Sun', platform: 'gba', genre: 'rpg', releaseYear: 2001, developer: 'Camelot', publisher: 'Nintendo', description: 'A beautiful RPG with Djinn collection and Psynergy powers.' },
  { title: 'Golden Sun: The Lost Age', platform: 'gba', genre: 'rpg', releaseYear: 2002, developer: 'Camelot', publisher: 'Nintendo', description: 'The direct sequel and conclusion of the Golden Sun saga.' },
  { title: 'Pokemon Ruby', platform: 'gba', genre: 'rpg', releaseYear: 2002, developer: 'Game Freak', publisher: 'Nintendo', description: 'The third generation of Pokemon in the Hoenn region.' },
  { title: 'Pokemon Emerald', platform: 'gba', genre: 'rpg', releaseYear: 2004, developer: 'Game Freak', publisher: 'Nintendo', description: 'The definitive Gen 3 Pokemon experience with the Battle Frontier.' },
  { title: 'Advance Wars', platform: 'gba', genre: 'strategy', releaseYear: 2001, developer: 'Intelligent Systems', publisher: 'Nintendo', description: 'Turn-based military strategy with charming characters.' },
  { title: 'WarioWare, Inc.: Mega Microgames!', platform: 'gba', genre: 'puzzle', releaseYear: 2003, developer: 'Nintendo', publisher: 'Nintendo', description: 'Fast-paced microgame collection with bizarre humor.' },
  { title: 'Mario & Luigi: Superstar Saga', platform: 'gba', genre: 'rpg', releaseYear: 2003, developer: 'AlphaDream', publisher: 'Nintendo', description: 'The Mario brothers\' first RPG adventure together.' },
  { title: 'Final Fantasy Tactics Advance', platform: 'gba', genre: 'strategy', releaseYear: 2003, developer: 'Square Enix', publisher: 'Square Enix', description: 'Tactical RPG set in the magical world of Ivalice.' },
  { title: 'Sonic Advance', platform: 'gba', genre: 'platformer', releaseYear: 2001, developer: 'Sonic Team', publisher: 'Sega', description: 'Classic Sonic platforming on the GBA.' },
  { title: 'The Legend of Zelda: A Link to the Past / Four Swords', platform: 'gba', genre: 'adventure', releaseYear: 2002, developer: 'Nintendo', publisher: 'Nintendo', description: 'The SNES classic on GBA plus a new Four Swords co-op mode.' },
  { title: 'Astro Boy: Omega Factor', platform: 'gba', genre: 'beat-em-up', releaseYear: 2004, developer: 'Treasure', publisher: 'Sega', description: 'Treasure\'s incredible Astro Boy beat-em-up.' },
  { title: 'Drill Dozer', platform: 'gba', genre: 'platformer', releaseYear: 2005, developer: 'Game Freak', publisher: 'Nintendo', description: 'A heist game with a giant drill. Rumble pack built-in.' },
  { title: 'Mother 3', platform: 'gba', genre: 'rpg', releaseYear: 2006, developer: 'Brownie Brown', publisher: 'Nintendo', description: 'The legendary Japan-only EarthBound sequel.' },
  { title: 'Super Mario Advance', platform: 'gba', genre: 'platformer', releaseYear: 2001, developer: 'Nintendo', publisher: 'Nintendo', description: 'Enhanced port of Super Mario Bros. 2 with Mario Bros. classic.' },

  // ─── Sega Saturn (1995) ────────────────────────────
  { title: 'Panzer Dragoon Saga', platform: 'sega-saturn', genre: 'rpg', releaseYear: 1998, developer: 'Team Andromeda', publisher: 'Sega', description: 'A cult-classic RPG on the Sega Saturn with a unique battle system.' },
  { title: 'Radiant Silvergun', platform: 'sega-saturn', genre: 'shooter', releaseYear: 1998, developer: 'Treasure', publisher: 'Treasure', description: 'An acclaimed shoot-em-up with a unique weapon system.' },
  { title: 'Shining Force III', platform: 'sega-saturn', genre: 'strategy', releaseYear: 1998, developer: 'Camelot', publisher: 'Sega', description: 'A tactical RPG epic on the Sega Saturn.' },
  { title: 'NiGHTS into Dreams...', platform: 'sega-saturn', genre: 'action', releaseYear: 1996, developer: 'Sega', publisher: 'Sega', description: 'A surreal flying game with dual analog control.' },
  { title: 'Sega Rally Championship', platform: 'sega-saturn', genre: 'racing', releaseYear: 1995, developer: 'Sega AM3', publisher: 'Sega', description: 'Arcade rally racing perfection on Saturn.' },
  { title: 'Virtua Fighter 2', platform: 'sega-saturn', genre: 'fighting', releaseYear: 1995, developer: 'Sega', publisher: 'Sega', description: 'Arcade-perfect 3D fighting at 60 FPS.' },
  { title: 'Guardian Heroes', platform: 'sega-saturn', genre: 'beat-em-up', releaseYear: 1996, developer: 'Treasure', publisher: 'Sega', description: 'A brilliant beat-em-up with RPG elements and branching paths.' },
  { title: 'Dragon Force', platform: 'sega-saturn', genre: 'strategy', releaseYear: 1996, developer: 'Sega', publisher: 'Sega', description: '100 vs 100 unit battles in this epic strategy game.' },
  { title: 'Saturn Bomberman', platform: 'sega-saturn', genre: 'puzzle', releaseYear: 1996, developer: 'Hudson Soft', publisher: 'Hudson Soft', description: '10-player Bomberman mayhem. The best Bomberman game.' },
  { title: 'Fighting Vipers', platform: 'sega-saturn', genre: 'fighting', releaseYear: 1995, developer: 'Sega AM2', publisher: 'Sega', description: '3D fighter with armor-breaking mechanics.' },

  // ─── Atari 2600 (1977) ─────────────────────────────
  { title: 'Adventure', platform: 'atari-2600', genre: 'adventure', releaseYear: 1980, developer: 'Atari', publisher: 'Atari', description: 'One of the earliest action-adventure games.' },
  { title: 'Pitfall!', platform: 'atari-2600', genre: 'platformer', releaseYear: 1982, developer: 'Activision', publisher: 'Activision', description: 'Pitfall Harry swings through the jungle in this landmark platformer.' },
  { title: 'Space Invaders', platform: 'atari-2600', genre: 'shooter', releaseYear: 1980, developer: 'Atari', publisher: 'Atari', description: 'The arcade classic brought home. Defend Earth from aliens.' },
  { title: 'Activision Boxing', platform: 'atari-2600', genre: 'sports', releaseYear: 1981, developer: 'Activision', publisher: 'Activision', description: 'First-person boxing game.' },
  { title: 'Combat', platform: 'atari-2600', genre: 'shooter', releaseYear: 1977, developer: 'Atari', publisher: 'Atari', description: 'The pack-in game for the Atari 2600. Tank battles.' },
  { title: 'Yars\' Revenge', platform: 'atari-2600', genre: 'shooter', releaseYear: 1982, developer: 'Atari', publisher: 'Atari', description: 'A unique shooter with a distinctive art style.' },
  { title: 'River Raid', platform: 'atari-2600', genre: 'shooter', releaseYear: 1982, developer: 'Activision', publisher: 'Activision', description: 'Vertical scrolling shooter on a river.' },
  { title: 'Frogger', platform: 'atari-2600', genre: 'action', releaseYear: 1982, developer: 'Parker Brothers', publisher: 'Parker Brothers', description: 'Guide frogs across traffic and rivers.' },

  // ─── PC Engine / TurboGrafx-16 (1987) ──────────────
  { title: 'Bonk\'s Adventure', platform: 'pc-engine', genre: 'platformer', releaseYear: 1990, developer: 'Red Company', publisher: 'NEC', description: 'A caveman-themed platformer starring Bonk.' },
  { title: 'Castlevania: Rondo of Blood', platform: 'pc-engine', genre: 'action', releaseYear: 1993, developer: 'Konami', publisher: 'Konami', description: 'Richter Belmont and Maria Renard battle Dracula on CD.' },
  { title: 'Lords of Thunder', platform: 'pc-engine', genre: 'shooter', releaseYear: 1993, developer: 'Red Company', publisher: 'Hudson Soft', description: 'A fantasy-themed shoot-em-up with a metal soundtrack.' },
  { title: 'Soldier Blade', platform: 'pc-engine', genre: 'shooter', releaseYear: 1992, developer: 'Hudson Soft', publisher: 'Hudson Soft', description: 'One of the best shoot-em-ups on the PC Engine.' },
  { title: 'Blazing Lazers', platform: 'pc-engine', genre: 'shooter', releaseYear: 1989, developer: 'Compile', publisher: 'NEC', description: 'Vertical shooter with weapon upgrades.' },
  { title: 'R-Type', platform: 'pc-engine', genre: 'shooter', releaseYear: 1988, developer: 'Irem', publisher: 'NEC', description: 'Side-scrolling shooter with the iconic Force pod.' },
  { title: 'Neutopia', platform: 'pc-engine', genre: 'adventure', releaseYear: 1989, developer: 'Hudson Soft', publisher: 'Hudson Soft', description: 'A Zelda-like action-adventure on PC Engine.' },
  { title: 'Ys Book I & II', platform: 'pc-engine', genre: 'rpg', releaseYear: 1989, developer: 'Falcom', publisher: 'Hudson Soft', description: 'Action RPG classic with bump combat and incredible CD soundtrack.' },
];
