services:
  - type: web
    name: retro-collection-tracker
    env: node
    region: frankfurt
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
