services:
  - type: web
    name: retro-tracker-backend
    env: node
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RAWG_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: 10000
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_PUBLIC_URL
        sync: false
